/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenusUniverseNehrunagarRouteImport } from './routes/venus-universe-nehrunagar'
import { Route as VenusUniverseAhmedabadRouteImport } from './routes/venus-universe-ahmedabad'
import { Route as UltraLuxuryApartmentsAhmedabadRouteImport } from './routes/ultra-luxury-apartments-ahmedabad'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ReraRegisteredProjectAhmedabadRouteImport } from './routes/rera-registered-project-ahmedabad'
import { Route as PropertyInNehrunagarAhmedabadRouteImport } from './routes/property-in-nehrunagar-ahmedabad'
import { Route as PropertyInAhmedabad7To10CroreRouteImport } from './routes/property-in-ahmedabad-7-to-10-crore'
import { Route as PropertyInAhmedabad5To7CroreRouteImport } from './routes/property-in-ahmedabad-5-to-7-crore'
import { Route as PropertyInAhmedabad10To15CroreRouteImport } from './routes/property-in-ahmedabad-10-to-15-crore'
import { Route as PenthouseAhmedabadRouteImport } from './routes/penthouse-ahmedabad'
import { Route as NriInvestmentAhmedabadRouteImport } from './routes/nri-investment-ahmedabad'
import { Route as NriBuyPropertyAhmedabadRouteImport } from './routes/nri-buy-property-ahmedabad'
import { Route as NewLuxuryProjectAhmedabadRouteImport } from './routes/new-luxury-project-ahmedabad'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LuxuryRealEstateAhmedabadRouteImport } from './routes/luxury-real-estate-ahmedabad'
import { Route as LuxuryApartmentsShivranjaniAhmedabadRouteImport } from './routes/luxury-apartments-shivranjani-ahmedabad'
import { Route as LuxuryApartmentsCgRoadAhmedabadRouteImport } from './routes/luxury-apartments-cg-road-ahmedabad'
import { Route as LuxuryApartmentsCentralAhmedabadRouteImport } from './routes/luxury-apartments-central-ahmedabad'
import { Route as LuxuryApartmentsAshramRoadAhmedabadRouteImport } from './routes/luxury-apartments-ashram-road-ahmedabad'
import { Route as Luxury5bhkAhmedabadRouteImport } from './routes/luxury-5bhk-ahmedabad'
import { Route as Luxury4bhkAhmedabadRouteImport } from './routes/luxury-4bhk-ahmedabad'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LargeCarpetAreaFlatsAhmedabadRouteImport } from './routes/large-carpet-area-flats-ahmedabad'
import { Route as HafeezContractorProjectAhmedabadRouteImport } from './routes/hafeez-contractor-project-ahmedabad'
import { Route as GatedCommunityAhmedabadRouteImport } from './routes/gated-community-ahmedabad'
import { Route as FlatsNearIimAhmedabadRouteImport } from './routes/flats-near-iim-ahmedabad'
import { Route as EoiRouteImport } from './routes/eoi'
import { Route as BestLuxuryProjectAhmedabadRouteImport } from './routes/best-luxury-project-ahmedabad'
import { Route as R5bhkNehrunagarAhmedabadRouteImport } from './routes/5bhk-nehrunagar-ahmedabad'
import { Route as R4bhkNehrunagarAhmedabadRouteImport } from './routes/4bhk-nehrunagar-ahmedabad'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIndexRouteImport } from './routes/insights/index'
import { Route as InsightsSlugRouteImport } from './routes/insights/$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicOtpRouteImport } from './routes/api/public/otp'
import { Route as ApiPublicNotifyLeadRouteImport } from './routes/api/public/notify-lead'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicHooksReconcileLeadsRouteImport } from './routes/api/public/hooks/reconcile-leads'

const VenusUniverseNehrunagarRoute = VenusUniverseNehrunagarRouteImport.update({
  id: '/venus-universe-nehrunagar',
  path: '/venus-universe-nehrunagar',
  getParentRoute: () => rootRouteImport,
} as any)
const VenusUniverseAhmedabadRoute = VenusUniverseAhmedabadRouteImport.update({
  id: '/venus-universe-ahmedabad',
  path: '/venus-universe-ahmedabad',
  getParentRoute: () => rootRouteImport,
} as any)
const UltraLuxuryApartmentsAhmedabadRoute =
  UltraLuxuryApartmentsAhmedabadRouteImport.update({
    id: '/ultra-luxury-apartments-ahmedabad',
    path: '/ultra-luxury-apartments-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReraRegisteredProjectAhmedabadRoute =
  ReraRegisteredProjectAhmedabadRouteImport.update({
    id: '/rera-registered-project-ahmedabad',
    path: '/rera-registered-project-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const PropertyInNehrunagarAhmedabadRoute =
  PropertyInNehrunagarAhmedabadRouteImport.update({
    id: '/property-in-nehrunagar-ahmedabad',
    path: '/property-in-nehrunagar-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const PropertyInAhmedabad7To10CroreRoute =
  PropertyInAhmedabad7To10CroreRouteImport.update({
    id: '/property-in-ahmedabad-7-to-10-crore',
    path: '/property-in-ahmedabad-7-to-10-crore',
    getParentRoute: () => rootRouteImport,
  } as any)
const PropertyInAhmedabad5To7CroreRoute =
  PropertyInAhmedabad5To7CroreRouteImport.update({
    id: '/property-in-ahmedabad-5-to-7-crore',
    path: '/property-in-ahmedabad-5-to-7-crore',
    getParentRoute: () => rootRouteImport,
  } as any)
const PropertyInAhmedabad10To15CroreRoute =
  PropertyInAhmedabad10To15CroreRouteImport.update({
    id: '/property-in-ahmedabad-10-to-15-crore',
    path: '/property-in-ahmedabad-10-to-15-crore',
    getParentRoute: () => rootRouteImport,
  } as any)
const PenthouseAhmedabadRoute = PenthouseAhmedabadRouteImport.update({
  id: '/penthouse-ahmedabad',
  path: '/penthouse-ahmedabad',
  getParentRoute: () => rootRouteImport,
} as any)
const NriInvestmentAhmedabadRoute = NriInvestmentAhmedabadRouteImport.update({
  id: '/nri-investment-ahmedabad',
  path: '/nri-investment-ahmedabad',
  getParentRoute: () => rootRouteImport,
} as any)
const NriBuyPropertyAhmedabadRoute = NriBuyPropertyAhmedabadRouteImport.update({
  id: '/nri-buy-property-ahmedabad',
  path: '/nri-buy-property-ahmedabad',
  getParentRoute: () => rootRouteImport,
} as any)
const NewLuxuryProjectAhmedabadRoute =
  NewLuxuryProjectAhmedabadRouteImport.update({
    id: '/new-luxury-project-ahmedabad',
    path: '/new-luxury-project-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LuxuryRealEstateAhmedabadRoute =
  LuxuryRealEstateAhmedabadRouteImport.update({
    id: '/luxury-real-estate-ahmedabad',
    path: '/luxury-real-estate-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const LuxuryApartmentsShivranjaniAhmedabadRoute =
  LuxuryApartmentsShivranjaniAhmedabadRouteImport.update({
    id: '/luxury-apartments-shivranjani-ahmedabad',
    path: '/luxury-apartments-shivranjani-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const LuxuryApartmentsCgRoadAhmedabadRoute =
  LuxuryApartmentsCgRoadAhmedabadRouteImport.update({
    id: '/luxury-apartments-cg-road-ahmedabad',
    path: '/luxury-apartments-cg-road-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const LuxuryApartmentsCentralAhmedabadRoute =
  LuxuryApartmentsCentralAhmedabadRouteImport.update({
    id: '/luxury-apartments-central-ahmedabad',
    path: '/luxury-apartments-central-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const LuxuryApartmentsAshramRoadAhmedabadRoute =
  LuxuryApartmentsAshramRoadAhmedabadRouteImport.update({
    id: '/luxury-apartments-ashram-road-ahmedabad',
    path: '/luxury-apartments-ashram-road-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const Luxury5bhkAhmedabadRoute = Luxury5bhkAhmedabadRouteImport.update({
  id: '/luxury-5bhk-ahmedabad',
  path: '/luxury-5bhk-ahmedabad',
  getParentRoute: () => rootRouteImport,
} as any)
const Luxury4bhkAhmedabadRoute = Luxury4bhkAhmedabadRouteImport.update({
  id: '/luxury-4bhk-ahmedabad',
  path: '/luxury-4bhk-ahmedabad',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LargeCarpetAreaFlatsAhmedabadRoute =
  LargeCarpetAreaFlatsAhmedabadRouteImport.update({
    id: '/large-carpet-area-flats-ahmedabad',
    path: '/large-carpet-area-flats-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const HafeezContractorProjectAhmedabadRoute =
  HafeezContractorProjectAhmedabadRouteImport.update({
    id: '/hafeez-contractor-project-ahmedabad',
    path: '/hafeez-contractor-project-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const GatedCommunityAhmedabadRoute = GatedCommunityAhmedabadRouteImport.update({
  id: '/gated-community-ahmedabad',
  path: '/gated-community-ahmedabad',
  getParentRoute: () => rootRouteImport,
} as any)
const FlatsNearIimAhmedabadRoute = FlatsNearIimAhmedabadRouteImport.update({
  id: '/flats-near-iim-ahmedabad',
  path: '/flats-near-iim-ahmedabad',
  getParentRoute: () => rootRouteImport,
} as any)
const EoiRoute = EoiRouteImport.update({
  id: '/eoi',
  path: '/eoi',
  getParentRoute: () => rootRouteImport,
} as any)
const BestLuxuryProjectAhmedabadRoute =
  BestLuxuryProjectAhmedabadRouteImport.update({
    id: '/best-luxury-project-ahmedabad',
    path: '/best-luxury-project-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const R5bhkNehrunagarAhmedabadRoute =
  R5bhkNehrunagarAhmedabadRouteImport.update({
    id: '/5bhk-nehrunagar-ahmedabad',
    path: '/5bhk-nehrunagar-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const R4bhkNehrunagarAhmedabadRoute =
  R4bhkNehrunagarAhmedabadRouteImport.update({
    id: '/4bhk-nehrunagar-ahmedabad',
    path: '/4bhk-nehrunagar-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOtpRoute = ApiPublicOtpRouteImport.update({
  id: '/api/public/otp',
  path: '/api/public/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyLeadRoute = ApiPublicNotifyLeadRouteImport.update({
  id: '/api/public/notify-lead',
  path: '/api/public/notify-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReconcileLeadsRoute =
  ApiPublicHooksReconcileLeadsRouteImport.update({
    id: '/api/public/hooks/reconcile-leads',
    path: '/api/public/hooks/reconcile-leads',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/4bhk-nehrunagar-ahmedabad': typeof R4bhkNehrunagarAhmedabadRoute
  '/5bhk-nehrunagar-ahmedabad': typeof R5bhkNehrunagarAhmedabadRoute
  '/best-luxury-project-ahmedabad': typeof BestLuxuryProjectAhmedabadRoute
  '/eoi': typeof EoiRoute
  '/flats-near-iim-ahmedabad': typeof FlatsNearIimAhmedabadRoute
  '/gated-community-ahmedabad': typeof GatedCommunityAhmedabadRoute
  '/hafeez-contractor-project-ahmedabad': typeof HafeezContractorProjectAhmedabadRoute
  '/large-carpet-area-flats-ahmedabad': typeof LargeCarpetAreaFlatsAhmedabadRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/luxury-4bhk-ahmedabad': typeof Luxury4bhkAhmedabadRoute
  '/luxury-5bhk-ahmedabad': typeof Luxury5bhkAhmedabadRoute
  '/luxury-apartments-ashram-road-ahmedabad': typeof LuxuryApartmentsAshramRoadAhmedabadRoute
  '/luxury-apartments-central-ahmedabad': typeof LuxuryApartmentsCentralAhmedabadRoute
  '/luxury-apartments-cg-road-ahmedabad': typeof LuxuryApartmentsCgRoadAhmedabadRoute
  '/luxury-apartments-shivranjani-ahmedabad': typeof LuxuryApartmentsShivranjaniAhmedabadRoute
  '/luxury-real-estate-ahmedabad': typeof LuxuryRealEstateAhmedabadRoute
  '/mcp': typeof McpRoute
  '/new-luxury-project-ahmedabad': typeof NewLuxuryProjectAhmedabadRoute
  '/nri-buy-property-ahmedabad': typeof NriBuyPropertyAhmedabadRoute
  '/nri-investment-ahmedabad': typeof NriInvestmentAhmedabadRoute
  '/penthouse-ahmedabad': typeof PenthouseAhmedabadRoute
  '/property-in-ahmedabad-10-to-15-crore': typeof PropertyInAhmedabad10To15CroreRoute
  '/property-in-ahmedabad-5-to-7-crore': typeof PropertyInAhmedabad5To7CroreRoute
  '/property-in-ahmedabad-7-to-10-crore': typeof PropertyInAhmedabad7To10CroreRoute
  '/property-in-nehrunagar-ahmedabad': typeof PropertyInNehrunagarAhmedabadRoute
  '/rera-registered-project-ahmedabad': typeof ReraRegisteredProjectAhmedabadRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/ultra-luxury-apartments-ahmedabad': typeof UltraLuxuryApartmentsAhmedabadRoute
  '/venus-universe-ahmedabad': typeof VenusUniverseAhmedabadRoute
  '/venus-universe-nehrunagar': typeof VenusUniverseNehrunagarRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/': typeof InsightsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/notify-lead': typeof ApiPublicNotifyLeadRoute
  '/api/public/otp': typeof ApiPublicOtpRoute
  '/api/public/hooks/reconcile-leads': typeof ApiPublicHooksReconcileLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/4bhk-nehrunagar-ahmedabad': typeof R4bhkNehrunagarAhmedabadRoute
  '/5bhk-nehrunagar-ahmedabad': typeof R5bhkNehrunagarAhmedabadRoute
  '/best-luxury-project-ahmedabad': typeof BestLuxuryProjectAhmedabadRoute
  '/eoi': typeof EoiRoute
  '/flats-near-iim-ahmedabad': typeof FlatsNearIimAhmedabadRoute
  '/gated-community-ahmedabad': typeof GatedCommunityAhmedabadRoute
  '/hafeez-contractor-project-ahmedabad': typeof HafeezContractorProjectAhmedabadRoute
  '/large-carpet-area-flats-ahmedabad': typeof LargeCarpetAreaFlatsAhmedabadRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/luxury-4bhk-ahmedabad': typeof Luxury4bhkAhmedabadRoute
  '/luxury-5bhk-ahmedabad': typeof Luxury5bhkAhmedabadRoute
  '/luxury-apartments-ashram-road-ahmedabad': typeof LuxuryApartmentsAshramRoadAhmedabadRoute
  '/luxury-apartments-central-ahmedabad': typeof LuxuryApartmentsCentralAhmedabadRoute
  '/luxury-apartments-cg-road-ahmedabad': typeof LuxuryApartmentsCgRoadAhmedabadRoute
  '/luxury-apartments-shivranjani-ahmedabad': typeof LuxuryApartmentsShivranjaniAhmedabadRoute
  '/luxury-real-estate-ahmedabad': typeof LuxuryRealEstateAhmedabadRoute
  '/mcp': typeof McpRoute
  '/new-luxury-project-ahmedabad': typeof NewLuxuryProjectAhmedabadRoute
  '/nri-buy-property-ahmedabad': typeof NriBuyPropertyAhmedabadRoute
  '/nri-investment-ahmedabad': typeof NriInvestmentAhmedabadRoute
  '/penthouse-ahmedabad': typeof PenthouseAhmedabadRoute
  '/property-in-ahmedabad-10-to-15-crore': typeof PropertyInAhmedabad10To15CroreRoute
  '/property-in-ahmedabad-5-to-7-crore': typeof PropertyInAhmedabad5To7CroreRoute
  '/property-in-ahmedabad-7-to-10-crore': typeof PropertyInAhmedabad7To10CroreRoute
  '/property-in-nehrunagar-ahmedabad': typeof PropertyInNehrunagarAhmedabadRoute
  '/rera-registered-project-ahmedabad': typeof ReraRegisteredProjectAhmedabadRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/ultra-luxury-apartments-ahmedabad': typeof UltraLuxuryApartmentsAhmedabadRoute
  '/venus-universe-ahmedabad': typeof VenusUniverseAhmedabadRoute
  '/venus-universe-nehrunagar': typeof VenusUniverseNehrunagarRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights': typeof InsightsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/notify-lead': typeof ApiPublicNotifyLeadRoute
  '/api/public/otp': typeof ApiPublicOtpRoute
  '/api/public/hooks/reconcile-leads': typeof ApiPublicHooksReconcileLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/4bhk-nehrunagar-ahmedabad': typeof R4bhkNehrunagarAhmedabadRoute
  '/5bhk-nehrunagar-ahmedabad': typeof R5bhkNehrunagarAhmedabadRoute
  '/best-luxury-project-ahmedabad': typeof BestLuxuryProjectAhmedabadRoute
  '/eoi': typeof EoiRoute
  '/flats-near-iim-ahmedabad': typeof FlatsNearIimAhmedabadRoute
  '/gated-community-ahmedabad': typeof GatedCommunityAhmedabadRoute
  '/hafeez-contractor-project-ahmedabad': typeof HafeezContractorProjectAhmedabadRoute
  '/large-carpet-area-flats-ahmedabad': typeof LargeCarpetAreaFlatsAhmedabadRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/luxury-4bhk-ahmedabad': typeof Luxury4bhkAhmedabadRoute
  '/luxury-5bhk-ahmedabad': typeof Luxury5bhkAhmedabadRoute
  '/luxury-apartments-ashram-road-ahmedabad': typeof LuxuryApartmentsAshramRoadAhmedabadRoute
  '/luxury-apartments-central-ahmedabad': typeof LuxuryApartmentsCentralAhmedabadRoute
  '/luxury-apartments-cg-road-ahmedabad': typeof LuxuryApartmentsCgRoadAhmedabadRoute
  '/luxury-apartments-shivranjani-ahmedabad': typeof LuxuryApartmentsShivranjaniAhmedabadRoute
  '/luxury-real-estate-ahmedabad': typeof LuxuryRealEstateAhmedabadRoute
  '/mcp': typeof McpRoute
  '/new-luxury-project-ahmedabad': typeof NewLuxuryProjectAhmedabadRoute
  '/nri-buy-property-ahmedabad': typeof NriBuyPropertyAhmedabadRoute
  '/nri-investment-ahmedabad': typeof NriInvestmentAhmedabadRoute
  '/penthouse-ahmedabad': typeof PenthouseAhmedabadRoute
  '/property-in-ahmedabad-10-to-15-crore': typeof PropertyInAhmedabad10To15CroreRoute
  '/property-in-ahmedabad-5-to-7-crore': typeof PropertyInAhmedabad5To7CroreRoute
  '/property-in-ahmedabad-7-to-10-crore': typeof PropertyInAhmedabad7To10CroreRoute
  '/property-in-nehrunagar-ahmedabad': typeof PropertyInNehrunagarAhmedabadRoute
  '/rera-registered-project-ahmedabad': typeof ReraRegisteredProjectAhmedabadRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/ultra-luxury-apartments-ahmedabad': typeof UltraLuxuryApartmentsAhmedabadRoute
  '/venus-universe-ahmedabad': typeof VenusUniverseAhmedabadRoute
  '/venus-universe-nehrunagar': typeof VenusUniverseNehrunagarRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/': typeof InsightsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/notify-lead': typeof ApiPublicNotifyLeadRoute
  '/api/public/otp': typeof ApiPublicOtpRoute
  '/api/public/hooks/reconcile-leads': typeof ApiPublicHooksReconcileLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/4bhk-nehrunagar-ahmedabad'
    | '/5bhk-nehrunagar-ahmedabad'
    | '/best-luxury-project-ahmedabad'
    | '/eoi'
    | '/flats-near-iim-ahmedabad'
    | '/gated-community-ahmedabad'
    | '/hafeez-contractor-project-ahmedabad'
    | '/large-carpet-area-flats-ahmedabad'
    | '/llms.txt'
    | '/luxury-4bhk-ahmedabad'
    | '/luxury-5bhk-ahmedabad'
    | '/luxury-apartments-ashram-road-ahmedabad'
    | '/luxury-apartments-central-ahmedabad'
    | '/luxury-apartments-cg-road-ahmedabad'
    | '/luxury-apartments-shivranjani-ahmedabad'
    | '/luxury-real-estate-ahmedabad'
    | '/mcp'
    | '/new-luxury-project-ahmedabad'
    | '/nri-buy-property-ahmedabad'
    | '/nri-investment-ahmedabad'
    | '/penthouse-ahmedabad'
    | '/property-in-ahmedabad-10-to-15-crore'
    | '/property-in-ahmedabad-5-to-7-crore'
    | '/property-in-ahmedabad-7-to-10-crore'
    | '/property-in-nehrunagar-ahmedabad'
    | '/rera-registered-project-ahmedabad'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/studio'
    | '/ultra-luxury-apartments-ahmedabad'
    | '/venus-universe-ahmedabad'
    | '/venus-universe-nehrunagar'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/insights/$slug'
    | '/insights/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/notify-lead'
    | '/api/public/otp'
    | '/api/public/hooks/reconcile-leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/4bhk-nehrunagar-ahmedabad'
    | '/5bhk-nehrunagar-ahmedabad'
    | '/best-luxury-project-ahmedabad'
    | '/eoi'
    | '/flats-near-iim-ahmedabad'
    | '/gated-community-ahmedabad'
    | '/hafeez-contractor-project-ahmedabad'
    | '/large-carpet-area-flats-ahmedabad'
    | '/llms.txt'
    | '/luxury-4bhk-ahmedabad'
    | '/luxury-5bhk-ahmedabad'
    | '/luxury-apartments-ashram-road-ahmedabad'
    | '/luxury-apartments-central-ahmedabad'
    | '/luxury-apartments-cg-road-ahmedabad'
    | '/luxury-apartments-shivranjani-ahmedabad'
    | '/luxury-real-estate-ahmedabad'
    | '/mcp'
    | '/new-luxury-project-ahmedabad'
    | '/nri-buy-property-ahmedabad'
    | '/nri-investment-ahmedabad'
    | '/penthouse-ahmedabad'
    | '/property-in-ahmedabad-10-to-15-crore'
    | '/property-in-ahmedabad-5-to-7-crore'
    | '/property-in-ahmedabad-7-to-10-crore'
    | '/property-in-nehrunagar-ahmedabad'
    | '/rera-registered-project-ahmedabad'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/studio'
    | '/ultra-luxury-apartments-ahmedabad'
    | '/venus-universe-ahmedabad'
    | '/venus-universe-nehrunagar'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/insights/$slug'
    | '/insights'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/notify-lead'
    | '/api/public/otp'
    | '/api/public/hooks/reconcile-leads'
  id:
    | '__root__'
    | '/'
    | '/4bhk-nehrunagar-ahmedabad'
    | '/5bhk-nehrunagar-ahmedabad'
    | '/best-luxury-project-ahmedabad'
    | '/eoi'
    | '/flats-near-iim-ahmedabad'
    | '/gated-community-ahmedabad'
    | '/hafeez-contractor-project-ahmedabad'
    | '/large-carpet-area-flats-ahmedabad'
    | '/llms.txt'
    | '/luxury-4bhk-ahmedabad'
    | '/luxury-5bhk-ahmedabad'
    | '/luxury-apartments-ashram-road-ahmedabad'
    | '/luxury-apartments-central-ahmedabad'
    | '/luxury-apartments-cg-road-ahmedabad'
    | '/luxury-apartments-shivranjani-ahmedabad'
    | '/luxury-real-estate-ahmedabad'
    | '/mcp'
    | '/new-luxury-project-ahmedabad'
    | '/nri-buy-property-ahmedabad'
    | '/nri-investment-ahmedabad'
    | '/penthouse-ahmedabad'
    | '/property-in-ahmedabad-10-to-15-crore'
    | '/property-in-ahmedabad-5-to-7-crore'
    | '/property-in-ahmedabad-7-to-10-crore'
    | '/property-in-nehrunagar-ahmedabad'
    | '/rera-registered-project-ahmedabad'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/studio'
    | '/ultra-luxury-apartments-ahmedabad'
    | '/venus-universe-ahmedabad'
    | '/venus-universe-nehrunagar'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/insights/$slug'
    | '/insights/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/notify-lead'
    | '/api/public/otp'
    | '/api/public/hooks/reconcile-leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R4bhkNehrunagarAhmedabadRoute: typeof R4bhkNehrunagarAhmedabadRoute
  R5bhkNehrunagarAhmedabadRoute: typeof R5bhkNehrunagarAhmedabadRoute
  BestLuxuryProjectAhmedabadRoute: typeof BestLuxuryProjectAhmedabadRoute
  EoiRoute: typeof EoiRoute
  FlatsNearIimAhmedabadRoute: typeof FlatsNearIimAhmedabadRoute
  GatedCommunityAhmedabadRoute: typeof GatedCommunityAhmedabadRoute
  HafeezContractorProjectAhmedabadRoute: typeof HafeezContractorProjectAhmedabadRoute
  LargeCarpetAreaFlatsAhmedabadRoute: typeof LargeCarpetAreaFlatsAhmedabadRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  Luxury4bhkAhmedabadRoute: typeof Luxury4bhkAhmedabadRoute
  Luxury5bhkAhmedabadRoute: typeof Luxury5bhkAhmedabadRoute
  LuxuryApartmentsAshramRoadAhmedabadRoute: typeof LuxuryApartmentsAshramRoadAhmedabadRoute
  LuxuryApartmentsCentralAhmedabadRoute: typeof LuxuryApartmentsCentralAhmedabadRoute
  LuxuryApartmentsCgRoadAhmedabadRoute: typeof LuxuryApartmentsCgRoadAhmedabadRoute
  LuxuryApartmentsShivranjaniAhmedabadRoute: typeof LuxuryApartmentsShivranjaniAhmedabadRoute
  LuxuryRealEstateAhmedabadRoute: typeof LuxuryRealEstateAhmedabadRoute
  McpRoute: typeof McpRoute
  NewLuxuryProjectAhmedabadRoute: typeof NewLuxuryProjectAhmedabadRoute
  NriBuyPropertyAhmedabadRoute: typeof NriBuyPropertyAhmedabadRoute
  NriInvestmentAhmedabadRoute: typeof NriInvestmentAhmedabadRoute
  PenthouseAhmedabadRoute: typeof PenthouseAhmedabadRoute
  PropertyInAhmedabad10To15CroreRoute: typeof PropertyInAhmedabad10To15CroreRoute
  PropertyInAhmedabad5To7CroreRoute: typeof PropertyInAhmedabad5To7CroreRoute
  PropertyInAhmedabad7To10CroreRoute: typeof PropertyInAhmedabad7To10CroreRoute
  PropertyInNehrunagarAhmedabadRoute: typeof PropertyInNehrunagarAhmedabadRoute
  ReraRegisteredProjectAhmedabadRoute: typeof ReraRegisteredProjectAhmedabadRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  UltraLuxuryApartmentsAhmedabadRoute: typeof UltraLuxuryApartmentsAhmedabadRoute
  VenusUniverseAhmedabadRoute: typeof VenusUniverseAhmedabadRoute
  VenusUniverseNehrunagarRoute: typeof VenusUniverseNehrunagarRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicNotifyLeadRoute: typeof ApiPublicNotifyLeadRoute
  ApiPublicOtpRoute: typeof ApiPublicOtpRoute
  ApiPublicHooksReconcileLeadsRoute: typeof ApiPublicHooksReconcileLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venus-universe-nehrunagar': {
      id: '/venus-universe-nehrunagar'
      path: '/venus-universe-nehrunagar'
      fullPath: '/venus-universe-nehrunagar'
      preLoaderRoute: typeof VenusUniverseNehrunagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venus-universe-ahmedabad': {
      id: '/venus-universe-ahmedabad'
      path: '/venus-universe-ahmedabad'
      fullPath: '/venus-universe-ahmedabad'
      preLoaderRoute: typeof VenusUniverseAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ultra-luxury-apartments-ahmedabad': {
      id: '/ultra-luxury-apartments-ahmedabad'
      path: '/ultra-luxury-apartments-ahmedabad'
      fullPath: '/ultra-luxury-apartments-ahmedabad'
      preLoaderRoute: typeof UltraLuxuryApartmentsAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rera-registered-project-ahmedabad': {
      id: '/rera-registered-project-ahmedabad'
      path: '/rera-registered-project-ahmedabad'
      fullPath: '/rera-registered-project-ahmedabad'
      preLoaderRoute: typeof ReraRegisteredProjectAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-in-nehrunagar-ahmedabad': {
      id: '/property-in-nehrunagar-ahmedabad'
      path: '/property-in-nehrunagar-ahmedabad'
      fullPath: '/property-in-nehrunagar-ahmedabad'
      preLoaderRoute: typeof PropertyInNehrunagarAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-in-ahmedabad-7-to-10-crore': {
      id: '/property-in-ahmedabad-7-to-10-crore'
      path: '/property-in-ahmedabad-7-to-10-crore'
      fullPath: '/property-in-ahmedabad-7-to-10-crore'
      preLoaderRoute: typeof PropertyInAhmedabad7To10CroreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-in-ahmedabad-5-to-7-crore': {
      id: '/property-in-ahmedabad-5-to-7-crore'
      path: '/property-in-ahmedabad-5-to-7-crore'
      fullPath: '/property-in-ahmedabad-5-to-7-crore'
      preLoaderRoute: typeof PropertyInAhmedabad5To7CroreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-in-ahmedabad-10-to-15-crore': {
      id: '/property-in-ahmedabad-10-to-15-crore'
      path: '/property-in-ahmedabad-10-to-15-crore'
      fullPath: '/property-in-ahmedabad-10-to-15-crore'
      preLoaderRoute: typeof PropertyInAhmedabad10To15CroreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penthouse-ahmedabad': {
      id: '/penthouse-ahmedabad'
      path: '/penthouse-ahmedabad'
      fullPath: '/penthouse-ahmedabad'
      preLoaderRoute: typeof PenthouseAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nri-investment-ahmedabad': {
      id: '/nri-investment-ahmedabad'
      path: '/nri-investment-ahmedabad'
      fullPath: '/nri-investment-ahmedabad'
      preLoaderRoute: typeof NriInvestmentAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nri-buy-property-ahmedabad': {
      id: '/nri-buy-property-ahmedabad'
      path: '/nri-buy-property-ahmedabad'
      fullPath: '/nri-buy-property-ahmedabad'
      preLoaderRoute: typeof NriBuyPropertyAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-luxury-project-ahmedabad': {
      id: '/new-luxury-project-ahmedabad'
      path: '/new-luxury-project-ahmedabad'
      fullPath: '/new-luxury-project-ahmedabad'
      preLoaderRoute: typeof NewLuxuryProjectAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury-real-estate-ahmedabad': {
      id: '/luxury-real-estate-ahmedabad'
      path: '/luxury-real-estate-ahmedabad'
      fullPath: '/luxury-real-estate-ahmedabad'
      preLoaderRoute: typeof LuxuryRealEstateAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury-apartments-shivranjani-ahmedabad': {
      id: '/luxury-apartments-shivranjani-ahmedabad'
      path: '/luxury-apartments-shivranjani-ahmedabad'
      fullPath: '/luxury-apartments-shivranjani-ahmedabad'
      preLoaderRoute: typeof LuxuryApartmentsShivranjaniAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury-apartments-cg-road-ahmedabad': {
      id: '/luxury-apartments-cg-road-ahmedabad'
      path: '/luxury-apartments-cg-road-ahmedabad'
      fullPath: '/luxury-apartments-cg-road-ahmedabad'
      preLoaderRoute: typeof LuxuryApartmentsCgRoadAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury-apartments-central-ahmedabad': {
      id: '/luxury-apartments-central-ahmedabad'
      path: '/luxury-apartments-central-ahmedabad'
      fullPath: '/luxury-apartments-central-ahmedabad'
      preLoaderRoute: typeof LuxuryApartmentsCentralAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury-apartments-ashram-road-ahmedabad': {
      id: '/luxury-apartments-ashram-road-ahmedabad'
      path: '/luxury-apartments-ashram-road-ahmedabad'
      fullPath: '/luxury-apartments-ashram-road-ahmedabad'
      preLoaderRoute: typeof LuxuryApartmentsAshramRoadAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury-5bhk-ahmedabad': {
      id: '/luxury-5bhk-ahmedabad'
      path: '/luxury-5bhk-ahmedabad'
      fullPath: '/luxury-5bhk-ahmedabad'
      preLoaderRoute: typeof Luxury5bhkAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury-4bhk-ahmedabad': {
      id: '/luxury-4bhk-ahmedabad'
      path: '/luxury-4bhk-ahmedabad'
      fullPath: '/luxury-4bhk-ahmedabad'
      preLoaderRoute: typeof Luxury4bhkAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/large-carpet-area-flats-ahmedabad': {
      id: '/large-carpet-area-flats-ahmedabad'
      path: '/large-carpet-area-flats-ahmedabad'
      fullPath: '/large-carpet-area-flats-ahmedabad'
      preLoaderRoute: typeof LargeCarpetAreaFlatsAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hafeez-contractor-project-ahmedabad': {
      id: '/hafeez-contractor-project-ahmedabad'
      path: '/hafeez-contractor-project-ahmedabad'
      fullPath: '/hafeez-contractor-project-ahmedabad'
      preLoaderRoute: typeof HafeezContractorProjectAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gated-community-ahmedabad': {
      id: '/gated-community-ahmedabad'
      path: '/gated-community-ahmedabad'
      fullPath: '/gated-community-ahmedabad'
      preLoaderRoute: typeof GatedCommunityAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flats-near-iim-ahmedabad': {
      id: '/flats-near-iim-ahmedabad'
      path: '/flats-near-iim-ahmedabad'
      fullPath: '/flats-near-iim-ahmedabad'
      preLoaderRoute: typeof FlatsNearIimAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eoi': {
      id: '/eoi'
      path: '/eoi'
      fullPath: '/eoi'
      preLoaderRoute: typeof EoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-luxury-project-ahmedabad': {
      id: '/best-luxury-project-ahmedabad'
      path: '/best-luxury-project-ahmedabad'
      fullPath: '/best-luxury-project-ahmedabad'
      preLoaderRoute: typeof BestLuxuryProjectAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/5bhk-nehrunagar-ahmedabad': {
      id: '/5bhk-nehrunagar-ahmedabad'
      path: '/5bhk-nehrunagar-ahmedabad'
      fullPath: '/5bhk-nehrunagar-ahmedabad'
      preLoaderRoute: typeof R5bhkNehrunagarAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/4bhk-nehrunagar-ahmedabad': {
      id: '/4bhk-nehrunagar-ahmedabad'
      path: '/4bhk-nehrunagar-ahmedabad'
      fullPath: '/4bhk-nehrunagar-ahmedabad'
      preLoaderRoute: typeof R4bhkNehrunagarAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/otp': {
      id: '/api/public/otp'
      path: '/api/public/otp'
      fullPath: '/api/public/otp'
      preLoaderRoute: typeof ApiPublicOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-lead': {
      id: '/api/public/notify-lead'
      path: '/api/public/notify-lead'
      fullPath: '/api/public/notify-lead'
      preLoaderRoute: typeof ApiPublicNotifyLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reconcile-leads': {
      id: '/api/public/hooks/reconcile-leads'
      path: '/api/public/hooks/reconcile-leads'
      fullPath: '/api/public/hooks/reconcile-leads'
      preLoaderRoute: typeof ApiPublicHooksReconcileLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R4bhkNehrunagarAhmedabadRoute: R4bhkNehrunagarAhmedabadRoute,
  R5bhkNehrunagarAhmedabadRoute: R5bhkNehrunagarAhmedabadRoute,
  BestLuxuryProjectAhmedabadRoute: BestLuxuryProjectAhmedabadRoute,
  EoiRoute: EoiRoute,
  FlatsNearIimAhmedabadRoute: FlatsNearIimAhmedabadRoute,
  GatedCommunityAhmedabadRoute: GatedCommunityAhmedabadRoute,
  HafeezContractorProjectAhmedabadRoute: HafeezContractorProjectAhmedabadRoute,
  LargeCarpetAreaFlatsAhmedabadRoute: LargeCarpetAreaFlatsAhmedabadRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  Luxury4bhkAhmedabadRoute: Luxury4bhkAhmedabadRoute,
  Luxury5bhkAhmedabadRoute: Luxury5bhkAhmedabadRoute,
  LuxuryApartmentsAshramRoadAhmedabadRoute:
    LuxuryApartmentsAshramRoadAhmedabadRoute,
  LuxuryApartmentsCentralAhmedabadRoute: LuxuryApartmentsCentralAhmedabadRoute,
  LuxuryApartmentsCgRoadAhmedabadRoute: LuxuryApartmentsCgRoadAhmedabadRoute,
  LuxuryApartmentsShivranjaniAhmedabadRoute:
    LuxuryApartmentsShivranjaniAhmedabadRoute,
  LuxuryRealEstateAhmedabadRoute: LuxuryRealEstateAhmedabadRoute,
  McpRoute: McpRoute,
  NewLuxuryProjectAhmedabadRoute: NewLuxuryProjectAhmedabadRoute,
  NriBuyPropertyAhmedabadRoute: NriBuyPropertyAhmedabadRoute,
  NriInvestmentAhmedabadRoute: NriInvestmentAhmedabadRoute,
  PenthouseAhmedabadRoute: PenthouseAhmedabadRoute,
  PropertyInAhmedabad10To15CroreRoute: PropertyInAhmedabad10To15CroreRoute,
  PropertyInAhmedabad5To7CroreRoute: PropertyInAhmedabad5To7CroreRoute,
  PropertyInAhmedabad7To10CroreRoute: PropertyInAhmedabad7To10CroreRoute,
  PropertyInNehrunagarAhmedabadRoute: PropertyInNehrunagarAhmedabadRoute,
  ReraRegisteredProjectAhmedabadRoute: ReraRegisteredProjectAhmedabadRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  UltraLuxuryApartmentsAhmedabadRoute: UltraLuxuryApartmentsAhmedabadRoute,
  VenusUniverseAhmedabadRoute: VenusUniverseAhmedabadRoute,
  VenusUniverseNehrunagarRoute: VenusUniverseNehrunagarRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicNotifyLeadRoute: ApiPublicNotifyLeadRoute,
  ApiPublicOtpRoute: ApiPublicOtpRoute,
  ApiPublicHooksReconcileLeadsRoute: ApiPublicHooksReconcileLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
