/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as EoiRouteImport } from './routes/eoi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicOtpRouteImport } from './routes/api/public/otp'
import { Route as ApiPublicNotifyLeadRouteImport } from './routes/api/public/notify-lead'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const EoiRoute = EoiRouteImport.update({
  id: '/eoi',
  path: '/eoi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOtpRoute = ApiPublicOtpRouteImport.update({
  id: '/api/public/otp',
  path: '/api/public/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyLeadRoute = ApiPublicNotifyLeadRouteImport.update({
  id: '/api/public/notify-lead',
  path: '/api/public/notify-lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eoi': typeof EoiRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/api/public/notify-lead': typeof ApiPublicNotifyLeadRoute
  '/api/public/otp': typeof ApiPublicOtpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eoi': typeof EoiRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/api/public/notify-lead': typeof ApiPublicNotifyLeadRoute
  '/api/public/otp': typeof ApiPublicOtpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eoi': typeof EoiRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/api/public/notify-lead': typeof ApiPublicNotifyLeadRoute
  '/api/public/otp': typeof ApiPublicOtpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eoi'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/studio'
    | '/api/public/notify-lead'
    | '/api/public/otp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eoi'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/studio'
    | '/api/public/notify-lead'
    | '/api/public/otp'
  id:
    | '__root__'
    | '/'
    | '/eoi'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/studio'
    | '/api/public/notify-lead'
    | '/api/public/otp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EoiRoute: typeof EoiRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  ApiPublicNotifyLeadRoute: typeof ApiPublicNotifyLeadRoute
  ApiPublicOtpRoute: typeof ApiPublicOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eoi': {
      id: '/eoi'
      path: '/eoi'
      fullPath: '/eoi'
      preLoaderRoute: typeof EoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/otp': {
      id: '/api/public/otp'
      path: '/api/public/otp'
      fullPath: '/api/public/otp'
      preLoaderRoute: typeof ApiPublicOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-lead': {
      id: '/api/public/notify-lead'
      path: '/api/public/notify-lead'
      fullPath: '/api/public/notify-lead'
      preLoaderRoute: typeof ApiPublicNotifyLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EoiRoute: EoiRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  ApiPublicNotifyLeadRoute: ApiPublicNotifyLeadRoute,
  ApiPublicOtpRoute: ApiPublicOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
